mall/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.documentation import include_docs_urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('xiao_shop.urls')),
    	# 需要查看drf的接口文档请配置
	path('docs/', include_docs_urls(title='XiaoShop API')), 
	# 需要DRF的可浏览API能力请配置 
	path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

xiao_shop/urls.py
from rest_framework.documentation import include_docs_urls
from django.urls import path, include
from .import views

app_name = "xiao_shop"

urlpatterns = [
    path('api/', include('xiao_shop.api.api_urls')),
    path('docs/', include_docs_urls(title='XiaoShop API')),
    path('api-auth/', include('rest_framework.urls')),
    
    # PC端
    path("", views.IndexView.as_view(), name="index"),
    path("all_category/", views.XiaoShopCategoryAllView.as_view(), name="all_category"),
    path("goods/<int:pk>/", views.XiaoShopCategoryView.as_view(), name="goods"),
    path("goods/<int:pk>/detail/", views.XiaoShopSPUDetailView.as_view(), name="goods_detail"),
    path("cart/", views.XiaoShopingCartView.as_view(), name="cart"),
    path("pay/", views.XiaoShopPayView.as_view(), name="pay"),
    path('user_profile/', views.XiaoShopUserProfileView.as_view(), name='user_profile'),
    path('user_orders/', views.XiaoShopUserOrdersView.as_view(), name='user_orders'),
    path('user_orders/<int:pk>/', views.XiaoShopUserOrdersDetailView.as_view(), name='user_orders_detail'),
    path('user_address/', views.XiaoShopUserAddressView.as_view(), name='user_address'),
    path("user_orders_sku/<int:pk>/", views.XiaoShopOrderSKUDetailView.as_view(), name="user_orders_sku_detail"),
    
    
    path("login/", views.XiaoShopLoginView.as_view(), name="login"),
    path("register/", views.XiaoShopRegisterView.as_view(), name="register"),
    path('logout/', views.XiaoShopLogoutView.as_view(), name='logout'),
    path('upload_img/', views.XiaoShopUploadImage.as_view(), name="upload_img"),
]

xiao_shop/models/order.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from .models import BaseModelMixin
from .goods import XiaoShopSKU

User = get_user_model()


class XiaoShopOrderInfo(BaseModelMixin):
    """订单信息"""

    class PayMethodChoices(models.IntegerChoices):
        CASH = 1, _('货到付款')
        ALIPAY = 2, _('支付宝')
        WECHATPAY = 3, _('微信支付')
        OVERPAY = 4, _('余额支付')

    class OrderStatusChoices(models.IntegerChoices):
        TOBPAY = 1, _('待支付')
        TOBDELIVER = 2, _('待发货')
        TOBRECEIVED = 3, _('待收货')
        TOBEVALUATE = 4, _('待评价')
        COMPLETE = 5, _('已完成')
        CANCELLED = 6, _('已取消')

    owner = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="用户")
    order_sn = models.CharField(
        blank=True, default="",
        unique=True, max_length=32,
        verbose_name="订单号", help_text="订单号")
    trade_sn = models.CharField(
        blank=True, null=True,
        unique=True, max_length=64,
        verbose_name="交易号", help_text="交易号")
    pay_status = models.IntegerField(
        choices=OrderStatusChoices.choices, default=1, verbose_name="支付状态", help_text="支付状态")
    pay_method = models.IntegerField(
        choices=PayMethodChoices.choices, default=2, verbose_name="支付方式", help_text="支付方式")
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2, verbose_name="商品总金额")
    order_mark = models.CharField(
        blank=True, default="", max_length=100, verbose_name="订单备注", help_text="订单备注")
    freight = models.DecimalField(
        max_digits=12, decimal_places=2, verbose_name="运费")
    name = models.CharField("签收人", max_length=50, default="")
    phone = models.CharField("手机号", max_length=11, default="")
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    address = models.CharField("地址", max_length=150)
    pay_time = models.DateTimeField(
        null=True, blank=True, verbose_name="支付时间", help_text="支付时间")

    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_sn

    @classmethod
    def get_pay_method(cls):
        # 支付方式列表字典
        return dict(cls.PayMethodChoices.choices)

    @classmethod
    def get_pay_default(cls):
        # 获取支付方式的默认值
        return cls._meta.get_field('pay_method').default


class XiaoShopOrderSKU(BaseModelMixin):
    """订单商品"""
    order = models.ForeignKey(XiaoShopOrderInfo, on_delete = models.PROTECT, verbose_name="订单")
    sku = models.ForeignKey(XiaoShopSKU, on_delete = models.PROTECT, blank=True, null=True, verbose_name="订单商品")
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField('单价', max_digits=18, decimal_places=2)
    is_commented = models.BooleanField(default=False, verbose_name="是否已评价")

    class Meta:
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name
    
    def __str__(self) -> str:
        return self.sku.spu.title


class XiaoShopAddress(BaseModelMixin):
    """收货地址
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    name = models.CharField("签收人", max_length=50)
    phone = models.CharField("手机号", max_length=11)
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    province = models.CharField(max_length=150, verbose_name="省")
    city = models.CharField(max_length=150, verbose_name="市")
    county = models.CharField(max_length=150, verbose_name="区/县")
    address = models.CharField(max_length=150, verbose_name="详细地址")
    is_default = models.BooleanField(default=False, verbose_name="设为默认")
    
    class Meta:
        verbose_name = "收货地址"
        verbose_name_plural = verbose_name
        constraints = [
            # 默认地址唯一约束
            models.UniqueConstraint(fields=('id', 'is_default'), name="unique_happy_addr")
        ]

    def __str__(self):
        return f'{self.name} {self.address}'
    
    @classmethod
    def get_default(cls, user, is_default=True):
        """[获取默认收货地址]

        Args:
            user (request.user): 当前登录用户对象

        Returns:
            [Queryset]: 所属用户的默认收货地址的queryset数据
        """
        return cls.objects.filter(owner=user, is_default=is_default)


class XiaoShopingCart(BaseModelMixin):
    # 购物车数据模型
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    sku = models.ForeignKey(XiaoShopSKU, on_delete=models.CASCADE, verbose_name="商品sku")
    num = models.PositiveIntegerField(default=1, verbose_name="数量")
    
    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = verbose_name
        constraints = [
            models.UniqueConstraint(fields=['owner', 'sku'], name='unique_owner_sku_happy')
        ]
        
    def __str__(self):
        return f'{self.owner}{self.sku}'
    
    @classmethod
    def get_cart_count(cls, user):
        # 当前用户的购物车数量
        return cls.objects.filter(owner=user).count()

xiao_shop/api/views/base.py
from rest_framework import viewsets
from rest_framework import mixins
from xiao_shop.models import XiaoShopBanner
from xiao_shop.api.serializers.base import XiaoShopBannerSerializer


class XiaoShopBannerViewsets(mixins.ListModelMixin, viewsets.GenericViewSet):
    """banner视图
    list:
        banner列表
    """
    serializer_class = XiaoShopBannerSerializer

    def get_queryset(self):
        return XiaoShopBanner.objects.filter(is_del=False)

xiao_shop/api/views/comment.py
from xml.dom import VALIDATION_ERR
from django.forms import ValidationError
from rest_framework import viewsets
from rest_framework import mixins
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication
from xiao_shop.api.permissions import IsOwnerOrReadOnly
from django.contrib.contenttypes.models import ContentType
from rest_framework.response import Response
from rest_framework import status
from ...models import XiaoShopRate, XiaoShopOrderSKU, XiaoShopOrderInfo
from ..serializers.comment import XiaoShopRateSerializer


class XiaoShopRateViewsets(mixins.ListModelMixin, mixins.CreateModelMixin, viewsets.GenericViewSet):
    """XiaoShopRate视图
    list:
        XiaoShopRate列表
    create:
        post打分接口
    """
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]
    queryset = XiaoShopRate.objects.all()
    serializer_class = XiaoShopRateSerializer
    authentication_classes = [SessionAuthentication]
      
    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        object_id = serializer.validated_data['object_id']
        
        order_sku = XiaoShopOrderSKU.objects.filter(order__owner=self.request.user, id=object_id)
        # 判断是否已经评价过，不可重复评价
        if order_sku.exists() and order_sku.first().is_commented:
            return Response({'error':'该商品已经评价！'}, status=status.HTTP_403_FORBIDDEN)
        # 判断订单状态是否已确认收货，确认收货后才可以评价！
        elif order_sku.exists() and not order_sku.first().is_commented and order_sku.first().order.pay_status==4:
            # 要评价的模型content_type
            content_type = ContentType.objects.get_for_model(XiaoShopOrderSKU)
            serializer.validated_data['content_type'] = content_type
            # 保存评价
            self.perform_create(serializer)
            # 标记为已评价
            order_sku.update(is_commented=True)
            # 如果该订单中的商品全部已评价，则修改该订单状态为已完成
            order = order_sku.first().order
            is_commented = XiaoShopOrderSKU.objects.filter(order__owner=request.user, order=order).values_list('is_commented', flat=True)
            if all(list(is_commented)):
                order.pay_status = 5
                order.save()
            headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
        else:
            return Response({'error':'商品不存在或该订单未确认收获！'}, status=status.HTTP_404_NOT_FOUND)
    

xiao_shop/api/views/goods.py
from rest_framework import viewsets
from rest_framework import mixins
# from django_filters import rest_framework as filters
from rest_framework import filters  # 筛选
from django_filters.rest_framework import DjangoFilterBackend  # 过滤
from rest_framework_extensions.cache.mixins import CacheResponseMixin
from xiao_shop.models import (
    XiaoShopCategory, XiaoShopBrand, XiaoShopSPU, XiaoShopSKU
)
from xiao_shop.api.serializers.goods import (
    XiaoShopeCategorySerializer, XiaoShopBrandSerializer, XiaoShopeCategoryDetailSerializer,
    XiaoShopSPUSerializer, XiaoShopSKUSerializer
)

from ..pagination import XiaoShopSKUPagination
from ..filters import (
    XiaoShopSKUFilter, XiaoShopSPUFilter, XiaoShopCategoryFilter
)
class XiaoShopCategoryViewsets(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):

    """
    分类列表视图，返回所有的商品列表数据
    list:
        商品分类列表数据
    """
   
    # filter_backends = [MyFilterBackend]
    filterset_class = XiaoShopCategoryFilter

    def get_serializer_class(self):
        """ 动态序列化 """
        if self.action == "list":
            return XiaoShopeCategorySerializer
        elif self.action == "retrieve":
            return XiaoShopeCategoryDetailSerializer
        return XiaoShopeCategorySerializer
    
    def get_queryset(self):
        """ 根据不同的请求返回不同的数据 """
        cates_queryset = XiaoShopCategory.objects.filter(is_del=False, parent__isnull=True)
        if self.action == "list":
            return cates_queryset
        elif self.action == "retrieve":
            return XiaoShopCategory.objects.filter(is_del=False)
        return cates_queryset


class XiaoShopBrandViewsets(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ XiaoShopBrand 商品品牌接口

    list:
        @params mixins.ListModelMixin
        返回商品品牌列表
    retrieve:
        @params mixins.RetrieveModelMixin
        返回商品品牌详情
    """
    queryset = XiaoShopBrand.objects.filter(is_del=False)
    serializer_class = XiaoShopBrandSerializer


class XiaoShopSPUViewsets(mixins.ListModelMixin, mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ SPU  
    spu可以全局缓存，因为不影响库存
    """
    queryset = XiaoShopSPU.objects.filter(is_del=False)
    serializer_class = XiaoShopSPUSerializer
    filterset_class = XiaoShopSPUFilter
    filter_backends = (DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter)
    search_fields = ("title", "sub_title")
    ordering_fields = ('skus__sell_price',)


class XiaoShopSKUViewsets(mixins.RetrieveModelMixin, viewsets.GenericViewSet):
    """ SKU  
    sku则不能全局缓存，因为库存会实时变动，需要更精细化控制
    """
    queryset = XiaoShopSKU.objects.filter(is_del=False)
    serializer_class = XiaoShopSKUSerializer
    filter_backends = (DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter)
    filterset_class = XiaoShopSKUFilter
    pagination_class = XiaoShopSKUPagination
    search_fields = ("spu__title", "spu__sub_title")
    ordering_fields = ('sell_price', 'sales', 'sort')

xiao_shop/views/order.py
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, DetailView, ListView
from django.core.cache import cache

from xiao_shop.conf import xiao_shop_settings
from .views import XiaoShopLoginRequiredMixin
from xiao_shop.models import (
    XiaoShopOrderInfo, XiaoShopAddress, XiaoShopSKU, XiaoShopOrderSKU)
from .views import BaseView


class XiaoShopingCartView(XiaoShopLoginRequiredMixin, BaseView, TemplateView):
    """ 购物车页面 """
    
    template_name = "xiao_shop/cart.html"


class XiaoShopUserProfileView(XiaoShopLoginRequiredMixin, BaseView, TemplateView):
    """ 用户中心 """
    
    template_name = "xiao_shop/user_profile.html"


class XiaoShopUserOrdersView(XiaoShopLoginRequiredMixin, BaseView, ListView):
    """ 我的订单 """
    template_name = "xiao_shop/user_orders.html"
    paginate_by = xiao_shop_settings.ORDERS_NUM

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = self.get_queryset()
        context['tobpay_orders'] = self.get_order_status(1)        # 待支付
        context['tobdeliver_orders'] = self.get_order_status(2)    # 待发货
        context['tobreceived_orders'] = self.get_order_status(3)   # 待收货
        context['tobevaluate_orders'] = self.get_order_status(4)   # 待评价
        context['complete_orders'] = self.get_order_status(5)      # 已完成
        context['cancelled_orders'] = self.get_order_status(6)     # 已取消
        return context

    def get_queryset(self):
        return XiaoShopOrderInfo.objects.filter(is_del=False, owner=self.request.user).order_by('-add_date')
    
    def get_order_status(self, status):
        queryset = self.get_queryset().filter(pay_status=status)
        return queryset

class XiaoShopUserOrdersDetailView(LoginRequiredMixin, BaseView, DetailView):
    """ 订单详情 """
    login_url = 'xiao_shop:login'
    redirect_field_name = 'redirect_to'
    template_name = "xiao_shop/user_orders_detail.html"
    context_object_name = "order"

    def get_queryset(self):
        return XiaoShopOrderInfo.objects.filter(is_del=False, owner=self.request.user)


class XiaoShopUserAddressView(XiaoShopUserProfileView):
    """ 
    收货地址管理 
    """
    template_name = "xiao_shop/user_address.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['address'] = XiaoShopAddress.objects.filter(is_del=False, owner=self.request.user)
        return context


class XiaoShopPayView(XiaoShopingCartView):
    """ 立即支付界面 """
    template_name = "xiao_shop/pay.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sku_data'] = self.get_cache_sku()
        return context

    def get_cache_sku(self):
        """ 
        点击立即购买后缓存当前SKU
        sku_id 
            前端传过来的sku的id值
        return
            sku_id存在返回缓存中的数据
            sku_id不存在返回一个空列表
        """
        sku_id = self.request.GET.get('sku_id')
        num = self.request.GET.get('num')
        if sku_id is None:
            return []
        if sku_id:
            key = f"{self.request.user.username}{sku_id}{num}"
            sku = cache.get(key)
            if not sku:
                skus = []
                for good in XiaoShopSKU.objects.filter(id=int(sku_id)):
                    sku_data = {}
                    sku_data['sku_id'] = sku_id
                    sku_data['spu_id'] = good.spu.id
                    sku_data['title'] = good.spu.title
                    sku_data['sub_title'] = good.spu.sub_title
                    sku_data['options'] = ','.join(good.get_options)
                    sku_data['sell_price'] = good.sell_price.to_eng_string()
                    sku_data['stocks'] = good.stocks
                    sku_data['main_picture'] = good.main_picture.url
                    sku_data['sku_total'] = (good.sell_price * int(num)).to_eng_string()
                    sku_data['num'] = num
                    skus.append(sku_data)
                cache.set(key, skus, 3600)
                sku = cache.get(key)
            return json.dumps(sku, ensure_ascii=False)
        
        
class XiaoShopOrderSKUDetailView(LoginRequiredMixin, BaseView, DetailView):
    
    template_name = "xiao_shop/order_sku_detail.html"
    context_object_name = "order_sku"
    
    def get_queryset(self):
        qs = XiaoShopOrderSKU.objects.filter(order__owner=self.request.user)
        return qs
    

xiao_shop/templates/xiao_shop/addr_modal.html
<b-modal v-model="isCardModalActive" :width="640" scroll="keep">
    <div class="card">
        <header class="card-header">
            <h1 class="card-header-title">
                选择收货地址
            </h1>
        </header>
        <div class="card-content">
            <div class="content">
                <a class="box" v-for="(item, index) in address" :key="index" @click="optAddress(item.id)">
                    <span class="tag is-primary" v-if="item.is_default">默认</span>
                    {$ item.name $}{$ item.phone $}
                    <p class="has-text-grey-dark">
                        {$ item.province $}{$ item.city $}{$ item.county $}{$ item.address $}
                    </p>
                </a>
                <p class="has-text-danger" v-if="!address.length">暂未添加收货地址，请直接在输入框填写收货地址即可！</p>
            </div>
        </div>
    </div>
</b-modal>

xiao_shop/templates/xiao_shop/order_sku_detail.html
{% extends 'xiao_shop/user_profile.html' %}
{% block extra_style %}{% endblock %}

{% block breadcrumb_content %}
<b-breadcrumb align="is-left">
    <b-breadcrumb-item tag='a' href="{% url 'xiao_shop:index' %}" >首页</b-breadcrumb-item>
    <b-breadcrumb-item tag='a' href="{% url 'xiao_shop:user_profile' %}">个人中心</b-breadcrumb-item>
    <b-breadcrumb-item tag='a' active>商品评价</b-breadcrumb-item>
</b-breadcrumb>
{% endblock %}

{% block menmber %}
<!-- <div class="box">
<article class="media">
    <figure class="media-left">
        <p class="image is-96x96">
            <img src="{{ MEDIA_URL }}{{ order_sku.sku.main_picture }}">
        </p>
    </figure>
    <div class="media-content">
        <h1 class="is-size">
            <a href="{% url 'xiao_shop:goods_detail' order_sku.sku.spu.id %}" target="_blank">
                {{ order_sku.sku.spu.title }}
            </a>
        </h1>
        <p class="has-text-grey-light pt-1 pb-1">规格: {{ order_sku.sku.options.all|join:"," }} </p>
        <p class="has-text-grey-light">
            <span class="pr-4">数量: {{ order_sku.count }}</span>
            <span>单价: {{ order_sku.price }}</span>
        </p>

    </div>
    {% comment %} <div class="media-right">
        {% if not goods.is_commented and order.pay_status == 5 %}
        <a href="{% url 'xiao_shop:user_orders_sku_detail' goods.id %}" class=" button is-small is-success is-outlined">去评价</a>
        
        {% elif goods.is_commented %}
        <button class="button is-small is-outlined">已评价</button>
        {% endif %}
    </div> {% endcomment %}
</article>
</div> -->
<div class="box1 is-shadowless">
    <h1>待评价商品：
        <a href="{% url 'xiao_shop:goods_detail' order_sku.sku.spu.id %}" target="_blank">
        {{ order_sku.sku.spu.title }}
        </a>
    </h1>
    <div class=" dropdown-divider"></div>
    <div class="is-block">
        <b-field label="评价：">
            <b-input v-model="comment" maxlength="200" type="textarea" placeholder="期待您诚恳的评价！"></b-input>
        </b-field>
        <div style="position: relative; top:-20px">
            <div class="is-pulled-left">
                <span >评分：</span>
            </div>
            <div>
                <b-rate v-model="rate" spaced :max="maxs" :texts="texts" show-text :custom-text="custom"></b-rate>
            </div>
            <div class="is-clearfix"></div>
        </div>
        {% comment %} 后端待处理 {% endcomment %}
        <b-button type="is-primary" expanded @click="addRate({{order_sku.id}})">发布评价</b-button>
    </div>
</div>
{% endblock %}

xiao_shop/templates/xiao_shop/user_orders_detail.html
{% extends 'xiao_shop/user_profile.html' %}

{% load tpl_tags %}

{% block menmber %}
<div class="box is-shadowless has-background-light">
    <h1 class="is-size-5">订单状态：{{ order.get_pay_status_display }}</h1>
    <input id="pay-status" hidden readonly type="number" value="{{ order.pay_status }}">
    <div class="mt-5">
        <template>
            <b-steps :has-navigation="hasNavigation" v-model="activeStep">
                <b-step-item label="待付款" icon="account-key"></b-step-item>
                <b-step-item label="待发货" icon="car"></b-step-item>
                <b-step-item label="待收货" icon="account-plus"></b-step-item>
                <b-step-item label="待评价" icon="comment-plus"></b-step-item>
                <b-step-item label="已完成" icon="store"></b-step-item>
            </b-steps>
        </template>
    </div>
</div>

<div class="box is-shadowless has-background-light">
    <h1 class="is-size-5">订单信息</h1>
    <div class="dropdown-divider"></div>
    <ul style="line-height: 2em;">
        <li><span>订单编号：</span> {{ order.order_sn }}</li>
        <li><span>订单日期：</span> {{ order.add_date }}</li>
        <li><span>支付状态：</span> {{ order.get_pay_status_display }}</li>
        <li><span>支付方式：</span> {{ order.get_pay_method_display }}</li>
        <li><span>买家备注：</span> {{ order.order_mark }}</li>
        <li><span>订单金额：</span> {{ order.total_amount }}</li>
    </ul>
</div>

<div class="box is-shadowless has-background-light">
    <h1 class="is-size-5">收货信息</h1>
    <div class="dropdown-divider"></div>
    <ul style="line-height: 2em;">
        <li><span>收货人：</span> {{ order.name }}</li>
        <li><span>收件电话：</span> {{ order.phone }}</li>
        <li><span>收货地址：</span> {{ order.address }}</li>
    </ul>
</div>

<div class="box is-shadowless has-background-light">
    <h1 class="is-size-5">商品信息</h1>
    <div class="dropdown-divider"></div>
    <div class="box">
        <p class="pb-3">订单日期：{{ order.add_date }}</p>
        {% for goods in order.xiaoshopordersku_set.all %}
        <article class="media">
            <figure class="media-left">
                <p class="image is-96x96">
                    <img src="{{ MEDIA_URL }}{{ goods.sku.main_picture }}">
                </p>
            </figure>
            <div class="media-content">
                <h1 class="is-size">
                    <a href="{% url 'xiao_shop:goods_detail' goods.sku.spu.id %}" target="_blank">
                        {{ goods.sku.spu.title }}
                    </a>
                </h1>
                <p class="has-text-grey-light pt-1 pb-1">规格: {{ goods.sku.options.all|join:"," }} </p>
                <p class="has-text-grey-light">
                    <span class="pr-4">数量: {{ goods.count }}</span>
                    <span>单价: {{ goods.price }}</span>
                </p>
    
            </div>
            <div class="media-right">
                <span class=" has-text-danger-dark">{{ order.get_pay_status_display }}</span>
            </div>
        </article>
        {% endfor %}
        <div class="is-block has-background-light p-3">
            <div class="is-pulled-left">
                <button class="button is-narrow is-small is-warning is-light has-text-weight-bold">实付：¥{{ order.total_amount }}</button> 
            </div>
            <div class="is-pulled-right">
                {% if order.pay_status == 1 %}
                <a class="button is-small is-info is-outlined" href="{% alipay_url order.order_sn %}" target="_blank">
                    <span class="pr-3 pt-1 pl-2">
                        <svg t="1632459990510" class="icon" viewBox="0 0 1024 1024" version="1.1"
                            xmlns="http://www.w3.org/2000/svg" p-id="2407" width="32" height="32">
                            <path
                                d="M1023.795 853.64v6.348a163.807 163.807 0 0 1-163.807 163.807h-696.18A163.807 163.807 0 0 1 0 859.988v-696.18A163.807 163.807 0 0 1 163.807 0h696.181a163.807 163.807 0 0 1 163.807 163.807V853.64z"
                                fill="#009FE9" p-id="2408"></path>
                            <path
                                d="M844.836 648.267c-40.952-14.333-95.623-34.809-156.846-57.128a949.058 949.058 0 0 0 90.094-222.573H573.325V307.14h245.711v-43.41l-245.71 2.458V143.33H472.173c-18.223 0-21.704 20.476-21.704 20.476v102.38H204.759v40.952h245.71v61.427H245.712v40.952h409.518a805.522 805.522 0 0 1-64.909 148.246c-128.384-42.795-266.186-77.604-354.233-55.08a213.564 213.564 0 0 0-112.003 63.27c-95.418 116.917-26.21 294.034 175.274 294.034 119.989 0 236.087-67.366 325.771-177.73 134.322 65.932 398.666 176.297 398.666 176.297V701.3s-32.352-4.095-178.96-53.033z m-563.702 144.97c-158.893 0-204.759-124.699-126.336-194.112a191.86 191.86 0 0 1 90.913-46.276c93.575-10.238 189.811 35.629 293.624 86.614-74.941 94.598-166.674 153.774-258.2 153.774z"
                                fill="#FFFFFF" p-id="2409"></path>
                        </svg>
                    </span>
                    支付宝支付
                </a>
                {% elif order.pay_status == 3 %}
                <a href="" class=" button is-small is-primary">确认收货</a>
                {% elif order.pay_status == 4 %}
                <!-- <a href="" class=" button is-small is-primary">再次购买</a> -->
                <a href="" class=" button is-small is-primary">去评价</a>
                {% endif %}
                <a href="{% url 'xiao_shop:user_orders_detail' order.id %}" class=" button is-small is-primary is-outlined">查看详情</a>
            </div>
            <div class="is-clearfix"></div>
        </div>
    </div>
</div>
{% endblock %}